name: Generate TOC in README

on:
  push:
    paths-ignore:
      - 'README.md'
    branches:
      - main
  workflow_dispatch:  # 수동 실행 가능

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run README generator
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/workspace \
            -e WORKSPACE_DIR=/workspace \
            -e CONTENT_DIR=contents \
            -e BLOG_URL=https://investment.advenoh.pe.kr \
            -e PROJECT_TITLE="Investment Insights Blog" \
            -e HITCOUNT_PATH=kenshin579/investment.advenoh.pe.kr \
            -e NETLIFY_BADGE_ID=31900f77-681f-4ace-8b3b-906936f57a60 \
            kenshin579/readme-generator:latest

      - name: Create commits
        run: |
          echo "username: ${{github.actor}}"

          git config user.name ${{github.actor}}
          git config user.email 'kenshin579@hotmail.com'
          git add README.md
          git commit -am "update README file"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: Update README file
          branch: readme-patches
          delete-branch: true
          title: '[AUTO] Update README file'
          body: |
            Update README file
          labels: |
            automated pr
          assignees: kenshin579
          reviewers: kenshin579
